# config.toml for EGFR C481S Mission

[vina_tool]
executable_path = "smina"
docking_runs = 3
screening_docking_runs = 1

[knowledge_base]
literature_dir = "data/literature"
db_path = "data/knowledge_base.lancedb"
table_name = "egfr_research" # New table name
embedding_model_name = "all-MiniLM-L6-v2"

[mission_parameters]
pdb_id = "1M17"
protein_file = "data/pdb/1M17.pdb"
ligand_name = "Erlotinib"
ligand_smiles = "COCCOc1cc2c(cc1OCCOC)ncnc2Nc1cccc(c1)C#C"

# Define key interactions for EGFR. These are CRITICAL for the IFP score.
# MET769 is the famous "hinge" residue in EGFR. Binding to it is essential.
# LEU768 and LEU820 form part of the hydrophobic pocket.
# Note: These are expert examples; refine them based on your literature analysis.
key_interactions = [
    "HBAcceptor-MET769",
    "HBDonor-MET769",
    "Hydrophobic-LEU768",
    "Hydrophobic-LEU820"
]

[simulation_box]
# These are the correct coordinates for 1M17 from your old config.
center_x = 21.857
center_y = 0.260
center_z = 52.761
size_x = 20.0
size_y = 20.0
size_z = 20.0

[autonomous_loop]
max_cycles = 5
hypothesis_batch_size = 3
tested_smiles = [
    "COCCOc1cc2c(cc1OCCOC)ncnc2Nc1cccc(c1)C#C"
]

[scoring]
# Weights for the new, more intelligent composite score.
w_affinity = -1.0
w_qed      = 5.0
w_sa_score = -1.0
w_ifp      = 10.0 # Strong reward for hitting the key hinge interactions

# Set a challenging but achievable initial gate. The V2 champion was -7.6.
# Let's start by requiring at least -7.0 to be considered.
affinity_threshold = -7.0

[md_simulation]
quick_test = true
quick_test_steps = 10000
simulation_steps = 500000
report_interval = 5000
protein_force_field = "amber14-all.xml"
protein_water_model = "amber14/tip3pfb.xml"
ligand_force_field  = "gaff-2.11"

[llm_models]
# The hierarchical model structure we engineered
hypothesis_model = "gemini-2.5-pro"
consultant_model = "gpt-5-2025-08-07"
report_intro_model = "gpt-5-2025-08-07"
report_methods_model = "gpt-5-2025-08-07"
report_discussion_model = "gpt-5-2025-08-07"
report_conclusion_model = "gpt-5-2025-08-07"